#!/bin/bash

set -xe

#	workaround for NVidia GPUs using PRIME configuration.
#	this will make output available on external ports.

test -f /usr/share/X11/xorg.conf.d/10-nvidia.conf && {
	echo 'Nvidia Proprietary Driver installed!, adding X11 configuration.'
		> /usr/share/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf printf "%s\n" \
			'Section "OutputClass"' \
			'	Identifier "nvidia"' \
			'	MatchDriver "nvidia-drm"' \
			'	Driver "nvidia"' \
			'	Option "PrimaryGPU" "Yes"' \
			'	Option "AllowEmptyInitialConfiguration" "true"' \
			'	Option "AllowExternalGpus" "true"' \
			'EndSection'

		> /usr/share/X11/xorg.conf.d/10-amdgpu.conf printf "%s\n" \
			'Section "OutputClass"' \
			'    Identifier "AMDgpu"' \
			'    MatchDriver "amdgpu"' \
			'    Driver "modsetting"' \
			'EndSection'

		> /usr/share/X11/xorg.conf.d/10-intel.conf printf "%s\n" \
			'Section "OutputClass"' \
			'    Identifier "Intel"' \
			'    MatchDriver "i915"' \
			'    Driver "modsetting"' \
			'EndSection'

		> /etc/modprobe.d/blacklist-nouveau.conf printf "%s\n" \
			'blacklist nouveau'
} || {
	echo 'Nvidia Proprietary Driver not installed!, skipping X11 configuration.'
}
